import React from "react";
import { Providers } from "./providers";
import Header from "./Header";
import Head from "next/head";
import { Flex } from "@chakra-ui/react";


export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <Flex flexDirection="column">
      <Head >
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Create Next App</title>
      </Head>
      
        <Header />
        <Providers >{children}</Providers>
      
    </Flex>
  );
}